allow-branch = ["main"]
shared-version = true
pre-release-commit-message = "Release version {{version}}."

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\[Unreleased\\] - ReleaseDate"
replace  =  "[Unreleased] - ReleaseDate\n\n## [{{version}}] - {{date}}"
exactly = 1
